### ISSUE TITLE
Unable to join sieges

### ISSUE THREAD

**Issue by 9koopa** [TheChildWalrus/SiegeMode#1]
This submod is amazing, and will definitely be of great use, but I have only one problem. When I start a siege, players are unable to join the siege due to permissions. Ordinarily, this is an easy fix, just adding the permission nodes to the player groups. However, since there is no permission nodes (or if there is, they are not listed), and no way for me to configure a workaround, I've come to see if you were able to fix this. If there is any additional information needed, please let me know.

Edit: I would like to note that this may become a problem for many servers, as a good portion use permission managing plugins, and would also need some way to be able to use the submod.

**Comment by Acult** [comment]
I have the same problem...

**Comment by 9koopa** [comment]
I have solved the problem! The nodes are:

siege.common.kit.CommandKit
siege.common.siege.CommandSiegePlay (Note this is the only one normal players should use)
siege.common.siege.CommandSiegeSetup

Thanks to MilkMC for this!

**Comment by MggMuggins** [comment]
Always send the kudos to Milk! He does a lot of hard work for you guys. :P
