### ISSUE TITLE
Repo Cleenup

### ISSUE THREAD

**Issue by ghost** [TheChildWalrus/SiegeMode#7]
> Turn Off Projects And Wiki Because They Arn’t Being Used.

**Comment by OtisGoodman** [comment]
Also You Should Close All The Ishwes That Haven’t Been Used In Over A Month.

**Comment by MggMuggins** [comment]
Mevans is the project manager, let him manage the repo. Make contributions or fork it if you think you can do better.

**Comment by ghost** [comment]
I don’t think you can change things like that with a fork.

**Comment by MggMuggins** [comment]
No you can't. The point is, let him manage his repo the way he will, and if you want to maintain a separate derivative codebase the way you want it to be managed, you're more than able to do so.
